### PR TITLE
Merge pull request #1 from izqui/not-authenticated

### PR DESCRIPTION
**Pull request by izqui**
Checks whether user was authenticated before background

### CODE REVIEW

**Comment by izqui** [comment]
sorry i don't know what i just did

**Comment by liu044100** [comment]
Hello, Jorge Izquierdo.

It doesn't matter,  thanks for previous pull request.

**Comment by izqui** [comment]
You are welcome! Sorry I thought I was merging my own non-autenticated
branch to my master.

I might be doing some other contributions. I have to ask something, why do
you non animate on presentAuthViewController when the mode is TouchID?

2015-09-21 11:31 GMT+02:00 Rain notifications@github.com:

**Comment by liu044100** [comment]
Because If animate present ViewController, the data of the user will be seen for a moment, so I set non animate.

But recently I have found even non animate, the presentation is not so quick when first launch the app, the data of the user still is seen for a moment.

I have a workaround In the example project, I add observer for the app first launch to add cover image for protect the data of the user. 

``` Objective-c
[[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(windowDidBecomeVisible:)
                                                 name:UIWindowDidBecomeKeyNotification
                                               object:nil]; 
```

and then below line is called,

``` Objective-c
-(void)windowDidBecomeVisible:(NSNotification*)notif{
    if ([SmileAuthenticator hasPassword]) {
        //iOS automatically snapshot screen, so if has password, use the _coverImageView cover the UIWindow for protecting user data.
        [self addCoverImageView];
        //remove the observer, because we just need it for the app first launch.
        [[NSNotificationCenter defaultCenter] removeObserver:self name:UIWindowDidBecomeKeyNotification object:nil];
    }
}
```

It make even the first launch, the data of the user cannot been seen.

If you have better solution, welcome to submit a pull request.

**Comment by izqui** [comment]
Interesting.

No, I was just curious. For my app, I don't show the auth view right away,
but when the user enters a certain section of the app. It is a bit weird if
you present it without an animation.

So, what I'm going to do is add a parameter on presentAuthViewController
with whether you want the presentation to be animated or not.

2015-09-21 11:46 GMT+02:00 Rain notifications@github.com:

**Comment by liu044100** [comment]
Feel free to make SmileTouchID customizable :-)

**Pull request closed without merging**
